name:                rapid-example
version:             0.1.0.0
github:              "futurefinance/rapid"
author:              "Ben Ford"
maintainer:          "bford@futurefinance.com"
copyright:           "2020 Future Finance"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/futurefinance/rapid#readme>

default-extensions:
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DisambiguateRecordFields
- DuplicateRecordFields
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns
- PatternSynonyms
- NumericUnderscores
- PostfixOperators
- TupleSections
- BlockArguments

ghc-options:
- -fwarn-redundant-constraints
# - -fno-warn-partial-type-signatures


dependencies:
- base >= 4.7 && < 5
- aws-lambda-haskell-runtime
- aeson
- binary
- bytestring
- containers
- rapid
- hourglass
- http-api-data
- insert-ordered-containers
- lens
- servant
- servant-server
- singletons
- swagger2
- template-haskell
- th-lift-instances
- text
- vector
- wai
- wai-extra
- warp

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -Wno-partial-type-signatures
  - -Wno-unticked-promoted-constructors

tests:
  example-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rapid-example
    - hspec
    - tasty
    - tasty-hspec
    - tasty-ant-xml
    - tasty-hedgehog

_exe-defs: &exe-defaults
  source-dirs:         app
  ghc-options:
  - -threaded
  - -rtsopts
  - -O2
  - -static
  - -with-rtsopts=-N
  cc-options: -static
  ld-options: -static -pthread
  dependencies:
  - rapid-example

executables:
  generate-swagger:
    main:                generate-swagger.hs
    <<: *exe-defaults

  bootstrap:
    main:                bootstrap.hs
    <<: *exe-defaults

  run:
    main:                run.hs
    <<: *exe-defaults
