name:                raid
version:             0.1.0.0
github:              "cdodev/raid"
license:             BSD3
author:              "Ben Ford"
maintainer:          "ben@commando.dev"
copyright:           "2017 Ben Ford"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cdodev/raid#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  raid-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raid

tests:
  raid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raid
