name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Cache install Nix packages
      uses: nix-actions/cache-install@v1.0.6
      with:
        key: rapid-build
        nix_file: 'build.nix'

    - name: Build
      uses: cachix/cachix-action@v8
      with:
        name: rapid
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: static-haskell-nix
    - run: $(nix-build -A fullBuildScript --argstr projectDir $PWD)
